"""
notification_agent.py

AYURA Notification Agent

Responsible for:
- Clinical notifications
- Appointment reminders
- Workflow notifications
- Department notifications
- Patient notifications
- Alert delivery

NOTE:
This agent delivers notifications.
It never makes decisions about when or why
they should be sent.
"""

from datetime import datetime
from typing import Dict, List


class NotificationAgent:
    """
    Notification Intelligence Agent.

    Responsible for preparing and managing
    notifications generated by other AYURA
    components.
    """

    def __init__(self):
        self.notifications: List[Dict] = []

    # --------------------------------------------------
    # Create Notification
    # --------------------------------------------------

    def create(
        self,
        recipient: str,
        title: str,
        message: str,
        priority: str = "NORMAL"
    ) -> Dict:

        notification = {
            "recipient": recipient,
            "title": title,
            "message": message,
            "priority": priority.upper(),
            "status": "PENDING",
            "created_at": datetime.utcnow()
        }

        self.notifications.append(notification)

        return notification

    # --------------------------------------------------
    # Send Notification
    # --------------------------------------------------

    def send(self, notification: Dict) -> Dict:
        """
        Placeholder.

        Actual delivery will be handled
        by the notification service.
        """

        notification["status"] = "SENT"
        notification["sent_at"] = datetime.utcnow()

        return notification

    # --------------------------------------------------
    # Bulk Send
    # --------------------------------------------------

    def send_all(self):

        for notification in self.notifications:

            if notification["status"] == "PENDING":
                self.send(notification)

    # --------------------------------------------------
    # History
    # --------------------------------------------------

    def history(self):

        return self.notifications

    # --------------------------------------------------
    # Pending
    # --------------------------------------------------

    def pending(self):

        return [
            notification
            for notification in self.notifications
            if notification["status"] == "PENDING"
        ]

    # --------------------------------------------------
    # Summary
    # --------------------------------------------------

    def summary(self):

        pending = len(self.pending())

        return {
            "total_notifications": len(self.notifications),
            "pending": pending,
            "sent": len(self.notifications) - pending
        }

    # --------------------------------------------------
    # Reset
    # --------------------------------------------------

    def reset(self):

        self.notifications.clear()

    def __repr__(self):

        return (
            f"<NotificationAgent "
            f"notifications={len(self.notifications)}>"
        )


# Singleton
notification_agent = NotificationAgent()